Fix IncompatibleClassChangeError under Java 9
The itf flag of `visitMethodInsn` and `Handle` in ASM needs to be true
when the method is defined in an interface. Java 8 ignores this but Java
9 fails at runtime with:
java.lang.IncompatibleClassChangeError: Method ... must beInterfaceMethodref constant

This commit is inspired by similar changes in scalac, in particular see
7d51b3fd1569917cb804363bd418466a306f5c89 by Jason Zaugg
(from https://github.com/scala/scala/pull/5251) and
e619b033350a3378d650db4c3e5b1bfc83b73d81 by Lukas Rytz
(from https://github.com/scala/scala/pull/5293). This issue was also
discussed in https://github.com/scala/scala/pull/5452 (which does not
matter for Dotty since we do not run the backend optimizer).